name: Build Docker images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4

      - uses: NEXFI-KK/release-name-action@v1
        id: release-name
        with:
          replace-refs: master=latest

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: Build and push Docker SDK image
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}
          push: true
          tags: |
            ghcr.io/nexfi-kk/docternal:${{ steps.release-name.outputs.name }}
            ghcr.io/nexfi-kk/docternal:${{ github.sha }}
